### PR TITLE
Local configuration adaption to ensure consisten <C-j> mapping in vim

### PR DESCRIPTION
**Pull request by somedadaism**
This solves the issue on my system with Ubuntu. (Please double check.)
I am not sure how this fits best for macOS or arch, but adaption should be easy.

### CODE REVIEW

**Comment by Netherdrake** [comment]
I think a quicker solution might be to add this to `vimrc`:
```
let g:C_Ctrl_j = 0
```

**Comment by somedadaism** [comment]
Thanks for the hint should work fine now.

**Comment by Netherdrake** [comment]
Thank you :)

**Comment by somedadaism** [comment]
My pleasure. :+1:

**Pull request merged**
